/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package example.single

import kotlinx.serialization.*

import example.single.T
import example.single.Meta
import example.single.DataType

@Serializable
data class Meta(
  val foo: String
)

@Serializable
data class DataType(
        val bar: Double
)

@Serializable
data class ListResponse<T>(
  val data: List<T>,
  val meta: Meta
)

/**
 * @expand
 */
@Serializable
data class DataResponse(
  val data: List<DataType>,
  val meta: Meta
)
