/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package example

import kotlinx.serialization.*
import kotlinx.serialization.json.*

/**
 * @expand
 */
@Serializable
data class FormData(
  val firstName: String,
  val lastName: String,
  val email: String,
  val phone: String? = null,
  val url: String? = null
)
