/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package net.sarazan.martok

import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonContentPolymorphicSerializer
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject

/**
 * This is a comment2
 */
@Serializable
data class MyType(

  val prop1: Prop1,

  /**
   * This is a comment
   * poggings
   */
  val prop2: Prop2
) {

  @Serializable
  data class Prop1(

    val foo: String,

    val boz: String
  )

  @Serializable
  data class Prop2(
    val foo: String
  )
}

/**
 * @expand
 */
@Serializable
data class Computed(

  val prop1: String,

  val prop2: String
)

/**
 * @expand
 */
@Serializable
data class Computed2(

  val prop1: Prop1,

  /**
   * This is a comment
   * poggings
   */
  val prop2: Prop2
) {

  @Serializable
  data class Prop1(

    val foo: String,

    val boz: String
  )

  @Serializable
  data class Prop2(
    val foo: String
  )
}
