/****************************************************
** DO NOT EDIT THIS FILE BY HAND!                  **
** This file was automatically generated by Martok **
** More info at https://github.com/asarazan/martok **
*****************************************************/
package net.sarazan.martok

import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonContentPolymorphicSerializer
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject

@Serializable
data class MyType1(
  val propA: PropA
) {

  @Serializable
  data class PropA(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(

      val propB: PropB? = null,

      val propC: PropC? = null,

      val propD: PropD? = null
    ) {

      @Serializable
      data class PropB(
        val deep: Deep
      ) {

        @Serializable
        data class Deep(

          val propC: PropC? = null,

          val propD: PropD? = null
        ) {

          @Serializable
          data class PropC(
            val deep: MyType4
          )

          @Serializable
          data class PropD(
            /**
             * Deep comment
             */
            val deep: String
          )
        }
      }

      @Serializable
      data class PropC(
        val deep: MyType4
      )

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }
}

@Serializable
data class MyType2(
  val propB: PropB
) {

  @Serializable
  data class PropB(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(

      val propC: PropC? = null,

      val propD: PropD? = null
    ) {

      @Serializable
      data class PropC(
        val deep: MyType4
      )

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }
}

@Serializable
data class MyType3(
  val propC: PropC
) {

  @Serializable
  data class PropC(
    val deep: MyType4
  )
}

@Serializable
data class MyType4(
  val propD: PropD
) {

  @Serializable
  data class PropD(
    /**
     * Deep comment
     */
    val deep: String
  )
}

@Serializable
data class MyType5(

  val propA: PropA? = null,

  val propB: PropB? = null,

  val propC: PropC? = null,

  val propD: PropD? = null,

  val propE: PropE
) {

  @Serializable
  data class PropA(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(

      val propB: PropB? = null,

      val propC: PropC? = null,

      val propD: PropD? = null
    ) {

      @Serializable
      data class PropB(
        val deep: Deep
      ) {

        @Serializable
        data class Deep(

          val propC: PropC? = null,

          val propD: PropD? = null
        ) {

          @Serializable
          data class PropC(
            val deep: MyType4
          )

          @Serializable
          data class PropD(
            /**
             * Deep comment
             */
            val deep: String
          )
        }
      }

      @Serializable
      data class PropC(
        val deep: MyType4
      )

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }

  @Serializable
  data class PropB(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(

      val propC: PropC? = null,

      val propD: PropD? = null
    ) {

      @Serializable
      data class PropC(
        val deep: MyType4
      )

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }

  @Serializable
  data class PropC(
    val deep: MyType4
  )

  @Serializable
  data class PropD(
    /**
     * Deep comment
     */
    val deep: String
  )

  @Serializable
  data class PropE(
    val deep: MyType4
  )
}

/**
 * @expand
 */
@Serializable
data class Computed(

  val propA: PropA? = null,

  val propE: PropE? = null,

  val propB: PropB? = null,

  val propC: PropC? = null,

  val propD: PropD? = null
) {

  @Serializable
  data class PropA(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(

      val propB: PropB? = null,

      val propC: PropC? = null,

      val propD: PropD? = null
    ) {

      @Serializable
      data class PropB(
        val deep: Deep
      ) {

        @Serializable
        data class Deep(

          val propC: PropC? = null,

          val propD: PropD? = null
        ) {

          @Serializable
          data class PropC(
            val deep: Deep
          ) {

            @Serializable
            data class Deep(
              val propD: PropD
            ) {

              @Serializable
              data class PropD(
                /**
                 * Deep comment
                 */
                val deep: String
              )
            }
          }

          @Serializable
          data class PropD(
            /**
             * Deep comment
             */
            val deep: String
          )
        }
      }

      @Serializable
      data class PropC(
        val deep: Deep
      ) {

        @Serializable
        data class Deep(
          val propD: PropD
        ) {

          @Serializable
          data class PropD(
            /**
             * Deep comment
             */
            val deep: String
          )
        }
      }

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }

  @Serializable
  data class PropE(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(
      val propD: PropD
    ) {

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }

  @Serializable
  data class PropB(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(

      val propC: PropC? = null,

      val propD: PropD? = null
    ) {

      @Serializable
      data class PropC(
        val deep: Deep
      ) {

        @Serializable
        data class Deep(
          val propD: PropD
        ) {

          @Serializable
          data class PropD(
            /**
             * Deep comment
             */
            val deep: String
          )
        }
      }

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }

  @Serializable
  data class PropC(
    val deep: Deep
  ) {

    @Serializable
    data class Deep(
      val propD: PropD
    ) {

      @Serializable
      data class PropD(
        /**
         * Deep comment
         */
        val deep: String
      )
    }
  }

  @Serializable
  data class PropD(
    /**
     * Deep comment
     */
    val deep: String
  )
}
